Added haplotype_database to calls to main pipeline
broadinstitute/palantir-workflows pull request #34
Opened 2021-04-13 14:29 UTC by tmelman

2021-04-13 14:36 UTC, kachulis approved these changes
👍

2021-04-13 14:43 UTC, kachulis requested changes

2021-04-13 14:43 UTC, kachulis commented on ImputationPipeline/Validation/FullImputationPRSValidation.wdl
> +			haplotype_database = haplotype_database
shouldn't pass hapdb to validateScoring

2021-04-14 17:50 UTC, mollysacks approved these changes
lgtm

2021-04-14 17:53 UTC, merged